name: Test

on: push

jobs:
    test:
        name: Build and compare against the original binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: make -f Makefile.asm80
